// Code generated by MockGen. DO NOT EDIT.
// Source: shop.go

// Package shop is a generated GoMock package.
package shop

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDataLayer is a mock of DataLayer interface
type MockDataLayer struct {
	ctrl     *gomock.Controller
	recorder *MockDataLayerMockRecorder
}

// MockDataLayerMockRecorder is the mock recorder for MockDataLayer
type MockDataLayerMockRecorder struct {
	mock *MockDataLayer
}

// NewMockDataLayer creates a new mock instance
func NewMockDataLayer(ctrl *gomock.Controller) *MockDataLayer {
	mock := &MockDataLayer{ctrl: ctrl}
	mock.recorder = &MockDataLayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDataLayer) EXPECT() *MockDataLayerMockRecorder {
	return m.recorder
}

// GetShopByUserID mocks base method
func (m *MockDataLayer) GetShopByUserID(ctx context.Context, userID int64) (Shop, error) {
	ret := m.ctrl.Call(m, "GetShopByUserID", ctx, userID)
	ret0, _ := ret[0].(Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShopByUserID indicates an expected call of GetShopByUserID
func (mr *MockDataLayerMockRecorder) GetShopByUserID(ctx, userID interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShopByUserID", reflect.TypeOf((*MockDataLayer)(nil).GetShopByUserID), ctx, userID)
}
