version:  "3.2"
services:
    teratur:
        image: teratur
        build:
            context: .
            dockerfile: ../.docker/development.dockerfile
        volumes:
            - "../.:/go/src/github.com/essajiwa/teratur"
        environment:
            - ENV=development
        ports:
            - "4040:4040"
        depends_on:
            - redis
            - postgres
        command: [".dev/wait-for-it.sh","postgres:5432","--","refresh","run","-c",".dev/refresh.yml"]
        container_name: teratur
    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - 6378:6379
    postgres:
        image: postgres:alpine
        environment:
            POSTGRES_DB: teratur
            POSTGRES_PASSWORD: password
            POSTGRES_USER: biarteratur
            PGDATA: /var/lib/postgresql/data/teratur
        container_name: postgres
        volumes:
            - ../.docker/postgres-data:/var/lib/postgresql/data/teratur
            - ../.docker/database_scripts:/docker-entrypoint-initdb.d
        ports:
            - 5432:5432
    nsqlookupd:
        image: nsqio/nsq
        command: /nsqlookupd
        ports:
            - 4160:4160
            - 4161:4161
    nsqd:
        image: nsqio/nsq
        command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
        depends_on:
            - nsqlookupd
        ports:
            - 4150:4150
            - 4151:4151
    nsqadmin:
        image: nsqio/nsq
        command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
        depends_on:
            - nsqlookupd  
        ports:
            - 4171:4171
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
        command: elasticsearch -Ecluster.name=catalog -Ebootstrap.memory_lock=true -Ehttp.port=9200 -Ehttp.cors.allow-origin="*" -Ehttp.cors.enabled=true -Ehttp.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization -Ehttp.cors.allow-credentials=true -Expack.security.enabled=false
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ../.docker/elasticdata:/usr/share/elasticsearch/data:rw
        ports:
            - 9200:9200
    kibana:
        image: docker.elastic.co/kibana/kibana:7.5.0
        container_name: kibana
        ports:
            - "5601:5601"
        links:
            - elasticsearch
    jaeger:
        container_name: jaeger-all-in-one
        image: jaegertracing/all-in-one
        environment:
            - COLLECTOR_ZIPKIN_HTTP_PORT=9411
        ports:
            - 5775:5775/udp
            - 6831:6831/udp
            - 6832:6832/udp
            - 5778:5778
            - 16686:16686
            - 14268:14268
            - 9411:9411